import { ActivepiecesClient, type PieceMetadataFull, type PieceActionMeta } from './ap-client.js';

/**
 * Prop types from the Activepieces framework.
 */
const AUTH_PROP_TYPES = ['OAUTH2', 'SECRET_TEXT', 'BASIC_AUTH', 'CUSTOM_AUTH'];
const SKIP_PROP_TYPES = ['MARKDOWN']; // display-only

interface GeneratedActionConfig {
  actionName: string;
  displayName: string;
  description: string;
  input: Record<string, unknown>;
  readiness: 'ready' | 'needs_input';
  /** Props that need manual user input */
  manualProps: { name: string; displayName: string; type: string; reason: string }[];
  /** All props with their generated values and metadata */
  propsDetail: PropDetail[];
}

interface PropDetail {
  name: string;
  displayName: string;
  type: string;
  required: boolean;
  generatedValue: unknown;
  needsManualInput: boolean;
  reason?: string;
}

export interface AutoGeneratedConfig {
  pieceName: string;
  pieceDisplayName: string;
  actions: GeneratedActionConfig[];
  summary: {
    totalActions: number;
    readyToTest: number;
    needsInput: number;
  };
}

/**
 * Auto-generate test configurations for all actions of a piece.
 */
export function generateTestConfig(pieceMeta: PieceMetadataFull): AutoGeneratedConfig {
  const actions: GeneratedActionConfig[] = [];

  for (const [actionName, actionMeta] of Object.entries(pieceMeta.actions)) {
    const config = generateActionConfig(actionName, actionMeta, pieceMeta);
    actions.push(config);
  }

  const readyToTest = actions.filter(a => a.readiness === 'ready').length;

  return {
    pieceName: pieceMeta.name,
    pieceDisplayName: pieceMeta.displayName,
    actions,
    summary: {
      totalActions: actions.length,
      readyToTest,
      needsInput: actions.length - readyToTest,
    },
  };
}

function generateActionConfig(
  actionName: string,
  action: PieceActionMeta,
  piece: PieceMetadataFull,
): GeneratedActionConfig {
  const input: Record<string, unknown> = {};
  const manualProps: GeneratedActionConfig['manualProps'] = [];
  const propsDetail: PropDetail[] = [];

  for (const [propName, propDef] of Object.entries(action.props || {})) {
    const prop = propDef as any;
    const propType: string = prop.type ?? 'UNKNOWN';

    // Skip auth props (handled by connection system)
    if (AUTH_PROP_TYPES.includes(propType)) continue;
    // Skip display-only props
    if (SKIP_PROP_TYPES.includes(propType)) continue;

    const { value, needsManual, reason } = generatePropValue(propName, prop, piece);

    input[propName] = value;

    if (needsManual) {
      manualProps.push({
        name: propName,
        displayName: prop.displayName ?? propName,
        type: propType,
        reason: reason!,
      });
    }

    propsDetail.push({
      name: propName,
      displayName: prop.displayName ?? propName,
      type: propType,
      required: prop.required ?? false,
      generatedValue: value,
      needsManualInput: needsManual,
      reason,
    });
  }

  return {
    actionName,
    displayName: action.displayName,
    description: action.description,
    input,
    readiness: manualProps.length === 0 ? 'ready' : 'needs_input',
    manualProps,
    propsDetail,
  };
}

function generatePropValue(
  propName: string,
  prop: any,
  piece: PieceMetadataFull,
): { value: unknown; needsManual: boolean; reason?: string } {
  const propType: string = prop.type ?? 'UNKNOWN';

  // If there's a default value, use it
  if (prop.defaultValue !== undefined && prop.defaultValue !== null) {
    return { value: prop.defaultValue, needsManual: false };
  }

  switch (propType) {
    case 'SHORT_TEXT':
      return { value: smartTextDefault(propName, prop, piece), needsManual: false };

    case 'LONG_TEXT':
      return { value: smartTextDefault(propName, prop, piece) || 'Test value from Piece Tester', needsManual: false };

    case 'NUMBER':
      return { value: smartNumberDefault(propName), needsManual: false };

    case 'CHECKBOX':
      return { value: false, needsManual: false };

    case 'DATE_TIME':
      return { value: new Date().toISOString(), needsManual: false };

    case 'COLOR':
      return { value: '#4c6ef5', needsManual: false };

    case 'STATIC_DROPDOWN':
      if (prop.options?.options?.length > 0) {
        return { value: prop.options.options[0].value, needsManual: false };
      }
      return { value: '', needsManual: true, reason: 'Static dropdown has no options' };

    case 'STATIC_MULTI_SELECT_DROPDOWN':
      if (prop.options?.options?.length > 0) {
        return { value: [prop.options.options[0].value], needsManual: false };
      }
      return { value: [], needsManual: false };

    case 'DROPDOWN':
      // Dynamic dropdown - depends on runtime data (e.g. spreadsheet list, channel list)
      return {
        value: '',
        needsManual: true,
        reason: `Dynamic dropdown "${prop.displayName ?? propName}" - select a value from your account`,
      };

    case 'MULTI_SELECT_DROPDOWN':
      return {
        value: [],
        needsManual: true,
        reason: `Multi-select dropdown "${prop.displayName ?? propName}" - select values from your account`,
      };

    case 'DYNAMIC':
      // Dynamic properties - depend on other prop values
      return {
        value: {},
        needsManual: true,
        reason: `Dynamic fields "${prop.displayName ?? propName}" - depends on other selections`,
      };

    case 'JSON':
      return { value: {}, needsManual: false };

    case 'OBJECT':
      return { value: {}, needsManual: false };

    case 'ARRAY':
      return { value: [], needsManual: false };

    case 'FILE':
      return { value: null, needsManual: true, reason: 'File upload required' };

    case 'CUSTOM':
      return { value: '', needsManual: true, reason: 'Custom property - needs manual value' };

    default:
      if (!prop.required) return { value: '', needsManual: false };
      return { value: '', needsManual: true, reason: `Unknown prop type: ${propType}` };
  }
}

/**
 * Generate smart text defaults based on prop name / context.
 */
function smartTextDefault(propName: string, prop: any, piece: PieceMetadataFull): string {
  const name = propName.toLowerCase();
  const displayName = (prop.displayName ?? '').toLowerCase();

  // Common patterns
  if (name.includes('title') || name.includes('name') || name.includes('subject'))
    return `Test ${piece.displayName} - ${new Date().toISOString().slice(0, 10)}`;
  if (name.includes('description') || name.includes('body') || name.includes('content') || name.includes('message') || name.includes('text'))
    return `This is a test from Piece Tester at ${new Date().toISOString()}`;
  if (name.includes('email'))
    return 'test@example.com';
  if (name.includes('url') || name.includes('link') || name.includes('webhook'))
    return 'https://httpbin.org/post';
  if (name.includes('query') || name.includes('search'))
    return 'test';
  if (name.includes('tag') || name.includes('label'))
    return 'piece-tester';
  if (name.includes('color'))
    return '#4c6ef5';
  if (name.includes('phone'))
    return '+1234567890';
  if (name.includes('address'))
    return '123 Test St';
  if (name.includes('city'))
    return 'Test City';
  if (name.includes('country'))
    return 'US';
  if (name.includes('zip') || name.includes('postal'))
    return '12345';
  if (name.includes('currency'))
    return 'USD';
  if (name.includes('amount') || name.includes('price'))
    return '10.00';
  if (name.includes('id') && !name.includes('description'))
    return ''; // IDs usually need real values
  if (name.includes('key'))
    return 'test_key';

  return `test_${propName}`;
}

function smartNumberDefault(propName: string): number {
  const name = propName.toLowerCase();
  if (name.includes('limit') || name.includes('count') || name.includes('max'))
    return 10;
  if (name.includes('page'))
    return 1;
  if (name.includes('offset') || name.includes('skip'))
    return 0;
  if (name.includes('timeout'))
    return 30;
  if (name.includes('amount') || name.includes('price'))
    return 10;
  if (name.includes('quantity') || name.includes('qty'))
    return 1;
  if (name.includes('row') || name.includes('column') || name.includes('index'))
    return 1;
  return 1;
}
